INSERT INTO Personagens (nome) VALUES ("Mickey Mouse");
INSERT INTO Personagens (nome) VALUES ("Minnie Mouse");
INSERT INTO Personagens (nome) VALUES ("Donald Duck");
INSERT INTO Personagens (nome) VALUES ("Pluto");
INSERT INTO Personagens (nome) VALUES ("Retro Mickey Mouse");
INSERT INTO Personagens (nome) VALUES ("Mickey Fantasia");
INSERT INTO Personagens (nome) VALUES ("Rockstar Mickey Mouse");
INSERT INTO Personagens (nome) VALUES ("Figment");
INSERT INTO Personagens (nome) VALUES ("Snow White");
INSERT INTO Personagens (nome) VALUES ("The Evil Queen");
INSERT INTO Personagens (nome) VALUES ("Jiminy Cricket");
INSERT INTO Personagens (nome) VALUES ("White Rabbit");
INSERT INTO Personagens (nome) VALUES ("Mad Hatter");
INSERT INTO Personagens (nome) VALUES ("Cheshire Cat");
INSERT INTO Personagens (nome) VALUES ("Peter Pan");
INSERT INTO Personagens (nome) VALUES ("Captain Hook");
INSERT INTO Personagens (nome) VALUES ("Tick Tock");
INSERT INTO Personagens (nome) VALUES ("Aurora");
INSERT INTO Personagens (nome) VALUES ("Cruella De Vil");
INSERT INTO Personagens (nome) VALUES ("Marie");
INSERT INTO Personagens (nome) VALUES ("Sebastian");
INSERT INTO Personagens (nome) VALUES ("Princess Belle");
INSERT INTO Personagens (nome) VALUES ("Chip");
INSERT INTO Personagens (nome) VALUES ("Jafar");
INSERT INTO Personagens (nome) VALUES ("Iago");
INSERT INTO Personagens (nome) VALUES ("Simba");
INSERT INTO Personagens (nome) VALUES ("Mulan");
INSERT INTO Personagens (nome) VALUES ("Mushu");
INSERT INTO Personagens (nome) VALUES ("Lilo");
INSERT INTO Personagens (nome) VALUES ("Tiana");
INSERT INTO Personagens (nome) VALUES ("Dr. Facilier");
INSERT INTO Personagens (nome) VALUES ("Bolt");
INSERT INTO Personagens (nome) VALUES ("Rapunzel");
INSERT INTO Personagens (nome) VALUES ("Pascal");
INSERT INTO Personagens (nome) VALUES ("Olaf");
INSERT INTO Personagens (nome) VALUES ("Clu");
INSERT INTO Personagens (nome) VALUES ("Jack Sparrow");
INSERT INTO Personagens (nome) VALUES ("Blackbeard");
INSERT INTO Personagens (nome) VALUES ("Sparky");
INSERT INTO Personagens (nome) VALUES ("Dr. Heinz Doof.");
INSERT INTO Personagens (nome) VALUES ("Rex");
INSERT INTO Personagens (nome) VALUES ("Sarge");
INSERT INTO Personagens (nome) VALUES ("Alien");
INSERT INTO Personagens (nome) VALUES ("Mr. Incredible");
INSERT INTO Personagens (nome) VALUES ("Violet Parr");
INSERT INTO Personagens (nome) VALUES ("Jack-Jack");
INSERT INTO Personagens (nome) VALUES ("Mike Wazowski");
INSERT INTO Personagens (nome) VALUES ("Boo");
INSERT INTO Personagens (nome) VALUES ("Don Carlton");
INSERT INTO Personagens (nome) VALUES ("Mack");
INSERT INTO Personagens (nome) VALUES ("Luigi");
INSERT INTO Personagens (nome) VALUES ("WALL-E");
INSERT INTO Personagens (nome) VALUES ("Kermit");
INSERT INTO Personagens (nome) VALUES ("CDA Agent");
INSERT INTO Personagens (nome) VALUES ("Fillmore");
INSERT INTO Personagens (nome) VALUES ("Jack");
INSERT INTO Personagens (nome) VALUES ("Lotso");
INSERT INTO Personagens (nome) VALUES ("Merida");
INSERT INTO Personagens (nome) VALUES ("Randall Boggs");
INSERT INTO Personagens (nome) VALUES ("Sid");
INSERT INTO Personagens (nome) VALUES ("Terri and Terry");
INSERT INTO Personagens (nome) VALUES ("Zurg");